name: release-publish artifact and trigger Azure to retrieve

on:
   release:
     types: [created]
   workflow_dispatch:

jobs:
  restore-build-publish:
    runs-on: ubuntu-latest

    steps:  
      - name: Get Last 2 Releases
        uses: octokit/graphql-action@v2.x
        id: get_latest_releases
        with:
          query: |
            query release($owner:String!,$repo:String!) {
              repository(owner:$owner,name:$repo) {
                releases(first:2) {
                  nodes {
                    tagName
                  }
                }
              }
            }
          variables: |
            owner: JesseBroxterman
            repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}         
          
      - name: Get Tag Name of Previous Release
        id: previous_release
        run: echo "tagName=${{ fromJson(steps.get_latest_releases.outputs.data).repository.releases.nodes[1].tagName }}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ steps.previous_release.outputs.tagName }}
          filters: |
            Shared:
            - '**/Common/**'
            - '**/Common.Web/**'
            - '**/Identity.BL/**'
            - '**/Identity.DAL/**'
            - '**/Identity.DM/**'
            - '**/Notify.BL/**'
            - '**/Notify.DAL/**'       
            - '**/Notify.DM/**'       
            - '**/PE.BL/**'
            - '**/PE.DAL/**'       
            - '**/PE.DM/**'       
            - '**/SW.BLL/**'
            - '**/SW.BLL.KanPay/**'
            - '**/SW.DAL/**'
            - '**/SW.DM/**'                
            External:
            - '${{ vars.SOLUTION_NAME }}/${{ vars.EXTERNAL_WEB_PROJECT }}/**'
            Internal:
            - '${{ vars.SOLUTION_NAME }}/${{ vars.INTERNAL_WEB_PROJECT }}/**'

      - name: Publish Internal
        if: (steps.changes.outputs.Internal == 'true' || steps.changes.outputs.Shared == 'true')
        run: dotnet publish ./${{ vars.SOLUTION_NAME }}/${{ vars.INTERNAL_WEB_PROJECT }}/${{ vars.INTERNAL_WEB_PROJECT }}.csproj --configuration Release

      - name: Upload Internal Artifact
        if: (steps.changes.outputs.Internal == 'true' || steps.changes.outputs.Shared == 'true')
        uses: actions/upload-artifact@v2
        with:
          name: ${{ vars.SOLUTION_NAME }}-Internal
          path: ./${{ vars.SOLUTION_NAME }}/${{ vars.INTERNAL_WEB_PROJECT }}/bin/Release/net6.0

      - uses: azure/pipelines@v1
        if: (steps.changes.outputs.Internal == 'true' || steps.changes.outputs.Shared == 'true')      
        with:
          azure-devops-project-url: ${{ vars.AZURE_DEVOPS_PROJECT_URL }}
          azure-pipeline-name: Internal-UAT-Deploy
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}



      - name: Publish External
        if: (steps.changes.outputs.External == 'true' || steps.changes.outputs.Shared == 'true')
        run: dotnet publish ./${{ vars.SOLUTION_NAME }}/${{ vars.EXTERNAL_WEB_PROJECT }}/${{ vars.EXTERNAL_WEB_PROJECT }}.csproj --configuration Release

      - name: Upload External Artifact
        if: (steps.changes.outputs.External == 'true' || steps.changes.outputs.Shared == 'true')
        uses: actions/upload-artifact@v2
        with:
          name: ${{ vars.SOLUTION_NAME }}-External
          path: ./${{ vars.SOLUTION_NAME }}/${{ vars.EXTERNAL_WEB_PROJECT }}/bin/Release/net6.0

      - uses: azure/pipelines@v1
        if: (steps.changes.outputs.External == 'true' || steps.changes.outputs.Shared == 'true')      
        with:
          azure-devops-project-url: ${{ vars.AZURE_DEVOPS_PROJECT_URL }}
          azure-pipeline-name: External-UAT-Deploy
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}            
